### ISSUE TITLE
Add-on is not compatible with Vaadin 24.4

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/WhatsappButton#14]
### Describe the bug

After upgrading the pom to 24.4.0.beta5, starting the demo fails with the following message:

```
(index):6 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-button" has already been used with this registry
    at window.customElements.define (http://127.0.0.1:8080/:6:829)
    at VAADIN/build/generated-flow-imports-DRaju_tl.js (http://127.0.0.1:8080/VAADIN/build/generated-flow-imports-DRaju_tl.js:3522:20)
    at __require (http://127.0.0.1:8080/VAADIN/build/generated-flow-imports-DRaju_tl.js:3:50)
    at http://127.0.0.1:8080/VAADIN/build/generated-flow-imports-DRaju_tl.js:44377:16
```

### Expected behavior

The demo should start with no issues

### Minimal reproducible example

1. Set `vaadin.version` in `v24` profile to 24.4.0.beta5 and add the following dependency
```
<dependencies>
    <dependency>
	<groupId>com.flowingcode.vaadin.addons.demo</groupId>
        <artifactId>commons-demo</artifactId>
        <version>4.0.0</version>
    </dependency>
</dependencies>
```

2. Run mvn jetty:run -Pv24

### Add-on Version

1.0.2-SNAPSHOT

### Vaadin Version

24.4.0.beta5

**Comment by paodb** [comment]
Was able to reproduce it just by adding the add-on dependency in a simple Vaadin 24.4.0.beta5 project. Not sure why it is happening though. It could be the fact that the web-component has vaadin components pinned in version 23.1.5? Or that it is using lit version 2? I tried several beta versions and it keeps failing. In 24.3.12 works fine.

**Comment by javier-godoy** [comment]
https://github.com/FlowingCode/fc-whatsapp-button/blob/dca3024c8416b44307ff482dee2e46ed1c5e98d7/package.json#L35-L39 has pinned dependencies "23.1.5". 

See https://github.com/FlowingCode/FontAwesomeIronIconset/issues/105 for a related issue

**Comment by paodb** [comment]
I updated vaadin dependencies to version ^23.3.35 in the web-component part and did a new release https://github.com/FlowingCode/fc-whatsapp-button/releases/tag/1.0.4. But when updating the server part to use this new version of the web-component, problem still persists.

**Comment by paodb** [comment]
As a follow up to my previous message, the problem is that updating the web-component part to ^23.3.35 is not going to work for vaadin 24.4 as ^ only includes versions in the 23 range. So it will try to use version 23.5.2: 

```
npm why node_modules/@flowingcode/fc-whatsapp-button/node_modules/@vaadin/button
@vaadin/button@23.5.2
node_modules/@flowingcode/fc-whatsapp-button/node_modules/@vaadin/button
  @vaadin/button@"^23.3.35" from @flowingcode/fc-whatsapp-button@1.0.4
  node_modules/@flowingcode/fc-whatsapp-button
    @flowingcode/fc-whatsapp-button@"1.0.4" from the root project
```
We need to create a new version of the web-component compatible with 24.4 and then update the flow part.
