### ISSUE TITLE
Button opens a blank screen

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/WhatsappButton#7]
I tried using the addon from a computer and the generated URL opened a blank screen `whatsapp://send/?phone=555&text=Hi!`
(replace 555 with an actual phone number). However, the following URL works: `https://api.whatsapp.com/send?phone=555`

**Comment by paodb** [comment]
If it's for use in computer please try using setRedirect(true).

**Comment by javier-godoy** [comment]
Astonishing. Can we have it documented? For the demo, we can initialize the checkbox depending on whether the device is mobile or not (https://stackoverflow.com/a/73731646/1297272)

I've seen that [Whatsapp documentation](https://faq.whatsapp.com/5913398998672934/) seems to recommend `https://wa.me/<number>`. Do you know if it is supported in mobile too?

**Comment by paodb** [comment]
About first question, it can be documented and the update on the demo sounds like a good idea. Should I create a new ticket?

About the second question, I have no idea.

**Comment by paodb** [comment]
Proposed updates in https://github.com/FlowingCode/WhatsappButton/issues/7#issuecomment-1455999973 will be handled in new different tickets #8 & #9.
